// <auto-generated />
using System;
using Area92.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Area92.Migrations
{
    [DbContext(typeof(AnimeContext))]
    [Migration("20220215091647_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Area92.Entities.Anime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("IMDBRating")
                        .HasColumnType("float");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4d1be218-dc3d-46fe-b973-e7c6b5dbbd35"),
                            IMDBRating = 8.6999999999999993,
                            ReleaseYear = 2019,
                            Title = "Demon Slayer: Kimetsu no Yaiba"
                        },
                        new
                        {
                            Id = new Guid("d9a5b2f3-ac8f-4586-92b8-9e1cbc2f2d0b"),
                            IMDBRating = 9.0,
                            ReleaseYear = 2013,
                            Title = "Attack on Titan"
                        },
                        new
                        {
                            Id = new Guid("824b31c4-baae-4f82-b3c8-c4d4631e76ca"),
                            IMDBRating = 9.0,
                            ReleaseYear = 2011,
                            Title = "Hunter × Hunter"
                        },
                        new
                        {
                            Id = new Guid("4287be31-a979-4601-9c28-960851bd564b"),
                            IMDBRating = 8.6999999999999993,
                            ReleaseYear = 2020,
                            Title = "Jujutsu Kaisen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
